--- #Ansible playbook for building image from Dockerfile and running a conatiner.
- hosts: all
  connection: ssh
  become: yes

  tasks:
    - name: build image
      command: docker build -t pranali/image1:1.1 /pranali
    - name: run container
      command: docker run -d -p 8070:8080 pranali/image1:1.1
